# Generated by Django 2.1.5 on 2020-06-17 20:29

from django.db import migrations, models
import zinnia.models_bases.entry


class Migration(migrations.Migration):

    dependencies = [
        ('zinnia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='video_cinco',
            field=models.FileField(blank=True, null=True, upload_to=zinnia.models_bases.entry.CoreEntry.get_imagen_video, verbose_name='video_cinco'),
        ),
        migrations.AddField(
            model_name='entry',
            name='video_cuantro',
            field=models.FileField(blank=True, null=True, upload_to=zinnia.models_bases.entry.CoreEntry.get_imagen_video, verbose_name='video_cuantro'),
        ),
        migrations.AddField(
            model_name='entry',
            name='video_dos',
            field=models.FileField(blank=True, null=True, upload_to=zinnia.models_bases.entry.CoreEntry.get_imagen_video, verbose_name='video_dos'),
        ),
        migrations.AddField(
            model_name='entry',
            name='video_seis',
            field=models.FileField(blank=True, null=True, upload_to=zinnia.models_bases.entry.CoreEntry.get_imagen_video, verbose_name='video_seis'),
        ),
        migrations.AddField(
            model_name='entry',
            name='video_tres',
            field=models.FileField(blank=True, null=True, upload_to=zinnia.models_bases.entry.CoreEntry.get_imagen_video, verbose_name='video_tres'),
        ),
    ]
